- name: Destroy a compute instance
  hosts: localhost
  tasks:
    - name: Destroy a VM
      os_server:
        name: "{{ item }}"
        state: absent
      with_items:
         - vm1
         - vm2
