- name: Manage new instances
  hosts: openstack_vms
  connection: ssh
  user: debian
  become: True
  roles:
#    - geerlingguy.ntp
    - geerlingguy.pip
    - geerlingguy.docker
#    - likg.csf

#  vars_files:
#    - variables_csf.yml
#    - ntp_conf.yml

  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - debian

  
  tasks: 
  - name: Install packages
    apt: name=lsof state=present

  - name: install saraza
    apt: name=tmux state=present

  - name: install web
    apt: name=lynx state=present

  - name: Webserver container.
    docker_container:
      name: dockertest
      image: kitematic/hello-world-nginx
      restart_policy: unless-stopped
      ports: 
       - "80:80"
      state: started
